#+TITLE:  Alexandre Giuliani
#+AUTHOR: AG
#+EMAIL:  (concat "alexandre.giuliani" at-sign "synchrotron-soleil.fr"

#+OPTIONS: toc:nil num:nil :org-html-postamble:t org-html-preamble:t tile:nil author:nil
#+OPTIONS: creator:t d:nil date:t stat:t inline:t e:t c:t broken-links:t 

#+HTML_HEAD: <link rel="icon" type="image/png" href="img/favicon-32x32.png" sizes="32x32" />
#+HTML_HEAD_EXTRA: <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js'></script>
#+HTML_HEAD_EXTRA: <script src='js/blog.js'></script>
#+HTML_HEAD_EXTRA: <link rel='stylesheet' type='text/css' href='css/style.css'>
#+HTML_HEAD_EXTRA: <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132913317-1"></script>
#+HTML_HEAD_EXTRA: <script>
#+HTML_HEAD_EXTRA:   window.dataLayer = window.dataLayer || [];
#+HTML_HEAD_EXTRA:   function gtag(){dataLayer.push(arguments);}
#+HTML_HEAD_EXTRA:   gtag('js', new Date());
#+HTML_HEAD_EXTRA:   gtag('config', 'UA-132913317-1');
#+HTML_HEAD_EXTRA: </script>

#+LINK_HOME:  https://agiuliani.xyz

#+HTML_DESCRIPTION: Personnal website
#+HTML_DESCRIPTION: chemistry, physical chemistry, spectroscopy
#+HTML_DESCRIPTION: science, chemistry, physical chemistry
#+HTML_DESCRIPTION: spectroscopy, mass spectrometry, radiation, UV, ultraviolet
#+HTML_KEYWORDS: chemistry, science, spectroscopy, interaction
#+LANGUAGE:   en
#+CATEGORY:   website

#+SUBTITLE: Spectroscopy & Spectrometry
#+HTML_DOCTYPE: html5



#+NAME: banner
#+BEGIN_EXPORT html
<div class="navbar">
  <ul>
    <li class="dropdown">
       <a class="active" href="https://agiuliani.xyz/index.html"
class="drobtn">Home</a>
       <div class="dropdown-content">
       </div>
    </li>
    <li class="dropdown">
       <a href="https://agiuliani.xyz/research.html"
class="drobtn">Research</a>
       <div class="dropdown-content">
          <a href="https://agiuliani.xyz/research.html#sec:interplay">Electronic structure</a>
	  <a href="https://agiuliani.xyz/research.html#sec:noncov">Non covalent interactions</a>
	  <a href="https://agiuliani.xyz/research.html#sec:structchem">Structural chemistry </a>
	  <a href="https://agiuliani.xyz/tools.html">Tools</a>
       </div>
    </li>
    <li class="dropdown">
       <a href="https://agiuliani.xyz/about.html"
class="drobtn">About me</a>
       <div class="dropdown-content">
       </div>
    </li>
    <li class="dropdown">
       <a href="https://agiuliani.xyz/production.html"
class="drobtn">Production</a>
       <div class="dropdown-content">
       <a href="https://agiuliani.xyz/production.html#sec:publications">Publications</a>
       <a href="https://agiuliani.xyz/production.html#sec:proceedings">Proceedings</a>
       <a href="https://agiuliani.xyz/production.html#sec:patents">Patents </a>
       <a href="https://agiuliani.xyz/production.html#sec:chapters">Book chapters </a>
       <a href="https://agiuliani.xyz/production.html#sec:oral_comm">Oral communications </a>
       <a href="https://agiuliani.xyz/production.html#sec:posters">Posters </a>
       <a href="https://agiuliani.xyz/production.html#sec:outreach">Outreach </a>
       </div>
    </li>
    <li class="dropdown">
       <a href="https://agiuliani.xyz/news.html"
class="drobtn">News</a>
       <div class="dropdown-content">
       </div>
    </li>
  </ul>
</div>
#+END_EXPORT


I am a [[https://agiuliani.xyz/about.html][chemist]] from INRA [fn:inra], the French National Institute for Agronomical Research working at the SOLEIL synchrotron radiation facility near Paris [fn:soleil]. 


My [[https://agiuliani.xyz/research.html][reseach]] is focussed mainly on electronic and geometric structures, which are arguably among the most fundamental piece of information on molecular systems.

To achieves these goals, several [[https://agiuliani.xyz/research.html#sec:newtools][tools]] based on /spectroscopy/, /mass spectrometry/ and their combinations have been developed.

My scientific production is detailed [[https://agiuliani.xyz/production.html][here]].

I picked an xyz domain name because it reminds me the =.xyz= format [fn:xyz] used to store chemical structures. An =.xyz= file is a representation of a molecular system, just as this site intends to be a representation of my scientific activities.

* Footnotes
[fn:inra] http://www.inra.fr/en/
[fn:soleil] https://www.synchrotron-soleil.fr/en
[fn:xyz] [[https://en.wikipedia.org/wiki/XYZ_file_format]]
[fn:2] 
