#+TITLE:  Alexandre Giuliani
#+AUTHOR: AG
#+EMAIL:  (concat "alexandre.giuliani" at-sign "synchrotron-soleil.fr"

#+OPTIONS: toc:nil num:nil :org-html-postamble:t org-html-preamble:t tile:nil author:nil
#+OPTIONS: creator:t d:nil date:t stat:t inline:t e:t c:t broken-links:t 

#+HTML_HEAD: <link rel="icon" type="image/png" href="img/favicon-32x32.png" sizes="32x32" />
#+HTML_HEAD_EXTRA: <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js'></script>
#+HTML_HEAD_EXTRA: <script src='js/blog.js'></script>
#+HTML_HEAD_EXTRA: <link rel='stylesheet' type='text/css' href='css/style.css'>
#+HTML_HEAD_EXTRA: <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132913317-1"></script>
#+HTML_HEAD_EXTRA: <script>
#+HTML_HEAD_EXTRA:   window.dataLayer = window.dataLayer || [];
#+HTML_HEAD_EXTRA:   function gtag(){dataLayer.push(arguments);}
#+HTML_HEAD_EXTRA:   gtag('js', new Date());
#+HTML_HEAD_EXTRA:   gtag('config', 'UA-132913317-1');
#+HTML_HEAD_EXTRA: </script>

#+LINK_HOME:  https://agiuliani.xyz

#+HTML_DESCRIPTION: Personnal website
#+HTML_DESCRIPTION: chemistry, physical chemistry, spectroscopy
#+HTML_DESCRIPTION: science, chemistry, physical chemistry
#+HTML_DESCRIPTION: spectroscopy, mass spectrometry, radiation, UV, ultraviolet
#+HTML_KEYWORDS: chemistry, science, spectroscopy, interaction
#+LANGUAGE:   en
#+CATEGORY:   website

#+SUBTITLE: Spectroscopy & Spectrometry
#+HTML_DOCTYPE: html5



#+NAME: banner
#+BEGIN_EXPORT html
<div class="navbar">
  <ul>
    <li class="dropdown">
       <a class="active" href="javascript:void(0)"
class="drobtn">Home</a>
       <div class="dropdown-content">
       </div>
    </li>
    <li><a href='research.html'>Research</a></li>
    <li><a href='tools.html'>Tools</a></li>
    <li><a href='colleagues.html'>Colleagues</a></li>
    <li><a href='about.html'>About me</a></li>
    <li><a href='production.html'>Production</a></li>
    <li><a href='outreach.html'>Outreach</a></li>
    <li><a href='news.html'>News</a></li>
  </ul>
</div>
#+END_EXPORT

* Home
Welcome here! My name is Alexandre Giuliani. Currently employed as a research engineer at [[http://www.inra.fr/en/Scientists-Students][INRA]] (Institut National de la Recherche Agronomique), I am on secondment at the [[https://www.synchrotron-soleil.fr/en][SOLEIL]] synchrotron radiation facility, near Paris (France) where I am working on the [[https://www.synchrotron-soleil.fr/en/beamlines/disco][DISCO]] beamline as a beamline scientist.

SOLEIL is a very large research infrastructure and provides the scientific community with an access to 28 beamlines delivering photon beams of high brilliance and stability over a wide wavelength range from the terahertz up to the hard X-rays. The [[https://www.synchrotron-soleil.fr/en/beamlines/disco][DISCO]] beamline, managed by [[https://cv.archives-ouvertes.fr/matthieu-refregiers][Matthieu Refrregiers]], makes use of visible, ultraviolet (UV) and vacuum-UV (VUV) photons on three experimental stations, namely fluorescence imaging, circular dichroism and the atmospheric pressure experimental (APEX) station. I am more specifically in charge of this last station.

In addition, I am a member of a team of INRA researchers at SOLEIL. Our mission is to help researchers and engineers from INRA to access the facility. We help improving proposals submitted by INRA researchers. In addition, we are visiting INRA centers across the country to present SOLEIL and its capabilities. We also maintain a monitoring of the technological developments appearing on synchrotron facilities.

I picked an xyz domain name because it reminds me the =.xyz= format [fn:1] used to store chemical structures. An =.xyz= file is a representation of a molecular system. This intent to be a representation of my scientific activities.

** Note
This site is made using [[https://orgmode.org/][Org]] mode based on the =CSS= file from Erik Sjöstrand ([[https://github.com/Kungsgeten/kungsgeten.github.io][Kungsgeten]]).

* Footnotes
[fn:1] [[https://en.wikipedia.org/wiki/XYZ_file_format]]
